# Generated by Django 3.2.5 on 2021-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_innovation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'verbose_name': 'Surveys',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
