# Generated by Django 3.2.5 on 2021-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_innovation', '0002_surveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'UsersDevices',
                'verbose_name_plural': 'UsersDevices',
            },
        ),
        migrations.AddField(
            model_name='surveys',
            name='device_id',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
