# Generated by Django 3.2.5 on 2021-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_innovation', '0003_auto_20210811_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='time_in_millis',
            field=models.IntegerField(default=0),
        ),
    ]
